### ISSUE TITLE
[Idea] Map Reduce / Transform functions

### ISSUE THREAD

**Issue by hktouw** [open-truss/open-truss#185]
In working on adding better [Array support for signals](https://github.com/open-truss/open-truss/pull/183), an idea for how we could perform map reduces / transforms occured to me.

These operations take in data, apply some arbitrary code to modify the data, then output the result. I believe we can create a system centered around signals and zod to handle this in a way that is natural for OT. We can create a signal type that has a [zod transform](https://zod.dev/?id=transform) function attached to it to process the data. When you want to transform a value, all you would need then is to use that signal type. e.g.

```yaml
workflow:
  signals:
    arraySignal:
      # This zod type has a transform that takes a string
      # and json parses it to an array. It also sets the type
      # of the signal to be an array of strings
      jsonColumn: StringArrayFromJsonString
  frames:
    - frame:
      view:
        component: OTUqiDataProvider
        props:
          source: trino-demo
          query: SELECT "['a', 'b']" AS jsonColumn
          output: [:arraySignal]
```

I spiked this out and the diff to support this was only a few lines of code and then a couple dozen more for the new signal type. https://github.com/open-truss/open-truss/commit/89af8108a6664b19d41003103a835f7d8093695d. We can probably make more improvements to make defining transforms simpler and remove more boiler plate. e.g. rather than defining json parsing functions for different types, we can define one and teach it how to accept a list of valid types / signal types and assert the parsed result matches those values. Here is an example, but it may require a bit of string parsing:

```yaml
      jsonColumn: FromJsonString(string[])
```

I don't think we have a use case yet for transforms, but this is something for us to consider if / when we cross that bridge.

@open-truss/engineers

**Comment by kmcq** [comment]
Very exciting idea @hktouw. We're certainly using signals in very interesting ways and I think this could make a lot of sense! Reading through https://github.com/open-truss/open-truss/commit/89af8108a6664b19d41003103a835f7d8093695d, it's great to see that you didn't have to modify the engine at all to get this working 😲 ✨ I agree that helping folks write these will be important.

**Comment by hktouw** [comment]
Thinking through another possible example, we may want to support the ability to path into objects and hoist out the nested property, making it accessible to components that probably don't match the original object's type. Not sure if this is a good idea or not, but what do you all think about something like? 

```yaml
workflow:
  signals:
    # takes data in the shape of { bio: { name: string, age: number } }
    # creates a signal of type { name: string, age: number } 
    bio: 'Dig(.bio, {
      name: string
      age: number
    })'
  frames:
    - frame:
      view:
        component: OTUqiDataProvider
        props:
          source: trino-demo
          query: SELECT CAST('{ "name": "mona", "age": 15 }' as JSON) AS bio
          output: [:bio]
```
