### ISSUE TITLE
No way to render text children

### ISSUE THREAD

**Issue by kmcq** [open-truss/open-truss#217]
i.e. this is impossible: `<Component>hello world</Component>`

While looking into https://github.com/open-truss/open-truss/issues/216, I noticed there's no way to render a string as a component's `children` because specifying `children` directly doesn't work and there's no way to tell the config that there is no component here, just text.

This config doesn't work despite `YourAppExampleComponent` [rendering children](https://github.com/open-truss/open-truss/blob/a2cb32590d745523a9004df60e8bd711713d784e/demo-app/src/open-truss/components/YourAppExampleComponent.tsx#L24):

```yaml
# This one doesn't error but also doesn't render "Hello!"
workflow:
  version: 1
  frames:
    - frame:
      view:
        component: YourAppExampleComponent
      props:
        children: "Hello!"
```
