### ISSUE TITLE
REST data provider

### ISSUE THREAD

**Issue by jonmagic** [open-truss/open-truss#41]
> Should this use uqi under the hood? The uqi source pattern to define the values needed to execute a query feels necessary (endpoint, creds) but unclear if the rest fits. REST != SQL and everything uqi does right now is SQL'ish or SQL adjacent.

Probably not. We'll try to implement this outside of uqi first. If there's enough overlap in the working implementation we'll migrate it to uqi.

## TODO

- [x] Sketch out yaml config for a rest call (w/ schema for endpoint responses)
- [x] Build `/api/synchronous-rest-call` server endpoint
- [x] Build non-uqi `OTRestDataProvider`
- [x] Implement feature to map JSON values from endpoint to a signal (e.g. object paths `.foo.bar[]`)
- [x] Implement signal injection into URL template string
- [x] Cleanup & write tests

**Comment by andrew-dillon** [comment]
@hktouw here's what I'm thinking for the yaml config:
```yaml
# Fetches and displays the total numbers of issues in the open-truss/open-truss repo
workflow:
  version: 1
  signals:
    results:
      total_count: string
  frames:
    - frame:
      view:
        component: OTRestDataProvider
        props:
          source: rest-demo
          path: /search/issues?q=repo:open-truss/open-truss+is:issue&per_page=1
          method: GET
          output: [:results]
          headers:
            - User-Agent: open-truss-rest-demo
      frames:
        - frame:
          view:
            component: DataDemo
            props:
              results: :results
```

The config for `source: rest-demo` will specify the protocol (e.g. `https`), auth headers (e.g. `Authorization: Bearer ...`), and the domain (e.g. `api.github.com`). 

It would be nice if we could parameterize the path, e.g.
```yaml
          path: /search/issues?q=repo:{repo_nwo}+is:issue&per_page={num_per_page}
```

I suppose the `OTRestDataProvider` could inject signals into the query string. What do you think?
